### PR TITLE
some updates

### PR DESCRIPTION
**Pull request by nwaxiomatic**

### CODE REVIEW

**Comment by llazzaro** [comment]
can you write a summary of the changes? I don't see references to any ticket.
I have to review each diff and it's sometimes difficult to track changes.

**Comment by nwaxiomatic** [comment]
Settings added:
USE_FULLCALENDAR - replaces use of daycalendar with fullcalendar
EVENT_NAME_PLACEHOLDER - sets the default event name when events are created through the drag/select function on fullcalendar
CHECK_OCCURRENCE_PERM_FUNC - allows for by-occurrence edit permissions

Templates fixed:
fullcalendar_script.html - this contains the javascript portion of the fullcalendar app (allows for embedding it outside of the main user hub, such as admin)
fullcalendar_modal.html - allows the user to pick editing/deleting single occurrence or whole event
fullcalendar.html - holds the modal and script 
event.html - fixed the bootstrap buttons/switched o glyphicons
occurrence.html - same as above, fixing issue #131 

Internals:
utils.py - updated the permission-checking functions to work with calendar/event/occurrence levels
views.py - updated all of the views to take into consideration permissions
events.py - fixed issue #141 

all of the fullcalendar additions should also solve issue #119

**Comment by nwaxiomatic** [comment]
I also just added a fix to issue #119 and issue #137.

**Comment by llazzaro** [comment]
thanks!!

**Pull request merged**
