### PR TITLE
calendar view permissions

### PR DESCRIPTION
**Pull request by nwaxiomatic**
Added a decorator @check_calendar_permissions to the calendar views.
This decorator checks the new variable CALENDAR_VIEW_PERM in settings
which is either True or False to decide if the
CHECK_CALENDAR_PERM_FUNCTION also effects the views of the calendars and
not just the event editing for the calendar.

### CODE REVIEW

**Comment by nwaxiomatic** [comment]
I don't understand what is failing here

**Comment by nwaxiomatic** [comment]
why is this the failing line in the Travis build?
    line 41: /home/travis/virtualenv/python2.7/bin/activate: No such file or directory

**Comment by llazzaro** [comment]
just bad luck! travis is working now.
let me review with more time your pull request.

but I think is ok

**Comment by llazzaro** [comment]
this will be release at 0.7.6

**Pull request merged**
