### PR TITLE
Add migration for calendar

### PR DESCRIPTION
**Pull request by flowerncsu**
When using django-scheduler, I found that I could not integrate my own models with django-scheduler's models without django creating a new migration inside the library, apparently due to changes that had not yet had a migration created. My coworker was able to replicate this issue, which causes problems when trying to collaborate on code, as each person's new commit will have a different name. This commit adds the needed migration so that the library contains everything it needs and can be used for collaborative projects.

### CODE REVIEW

**Comment by llazzaro** [comment]
I will review this today. thanks a lot for the pr.

**Comment by jdufresne** [comment]
For me personally, I'd name the migration something meaningful instead of the default timestamp. Something that reflects to the library consumer what the migration is changing. Right now it is named `0005_auto_20170714_1735.py`.

**Comment by llazzaro** [comment]
@jdufresne said. I will rename the migration of this pr.

**Comment by llazzaro** [comment]
this was merged on https://github.com/llazzaro/django-scheduler/commit/3b260c886f1695f99dbfbc1d846e5966e5c36600

**Pull request closed without merging**
