### PR TITLE
Master

### PR DESCRIPTION
**Pull request by Gustavosdo**
Hello lazzaro,
I made some corrections on the translation to Portuguese.
I also added a field in the model 'Event' giving possibility to choose the event color that appears in the full calendar...
I chose the spectrum library to create the widget, because it was the most complete plugin I know to do the job.

### CODE REVIEW

**Comment by llazzaro** [comment]
Not sure, but I think you overwrite migration 0001. could you create a new one? tests failed due to this cause.
I can check your fork and fix it, but I don't have much time to do it this weekend

**Comment by llazzaro** [comment]
thanks!

**Comment by llazzaro** [comment]
if the test is ok I will merge this

**Comment by Gustavosdo** [comment]
Thank llazzaro,
This library is amazing :)

**Comment by llazzaro** [comment]
this was merged into develop. it will be released on pipit on next release.
thanks!

**Comment by Gustavosdo** [comment]
Perfect, thanks again o/

**Pull request merged**
