### PR TITLE
Fixes TypeError on rules with single parameter args

### LINKED ISSUE #262: TypeError on "byweekday:0" Rule param
Hi, I'm getting TypeError on [events.py, Line 341](https://github.com/llazzaro/django-scheduler/blob/develop/schedule/models/events.py#L341) when using a Rule with a single argument, ie. `byweekday:0`. The method is trying to iterate an integer, because the `Rule.get_params()` method is not returning a list of values if there's a single argument.

I've got a fix ready which will make `Rule.get_params()` to always return a list of values, regardless of number of arguments.

I'll submit a PR soon.

### PR DESCRIPTION
**Pull request by rhblind**
Fixes #262 

This PR also contains a fix for [events.py line 190](https://github.com/llazzaro/django-scheduler/blob/develop/schedule/models/events.py#L190) which sometimes cause offset-aware dates to compare to offset-naive leading to a TypeError.

### CODE REVIEW

**Comment by rhblind** [comment]
Alright, I'm giving up having these tests pass right now..

**Comment by llazzaro** [comment]
@rhblind don't worry about tests, I will review them

**Comment by rhblind** [comment]
Alright =)
I closed the pull request, because I discovered some bugs. I'll submit a new when I've updated the code.

**Comment by llazzaro** [comment]
ok! great. let me know if you need some help, I want to merge this for the following version. thanks!

**Comment by mpaolino** [comment]
@rhblind @llazzaro  I think we might be duplicating efforts. Can you take a look at https://github.com/llazzaro/django-scheduler/pull/272? I honestly don't know what the heck is that year replacing doing [here](https://github.com/llazzaro/django-scheduler/pull/263/files#diff-76a3f2c62d8c0e654b7e348c65822601L190), its black magic and makes no sense to me.

**Comment by llazzaro** [comment]
@rhblind can you tell me which commit are you using? 
@mpaolino your changes are great!

**Comment by rhblind** [comment]
@llazzaro Sure 
I'm using `48cc64e689ad76bfd039c125f59419aa7368a8a2`.

**Pull request closed without merging**
