### PR TITLE
Add support for upcoming Django 2.0; drop support for Django < 1.11

### PR DESCRIPTION
**Pull request by jdufresne**
Django 2.0 is scheduled to be released later this year. See:

https://code.djangoproject.com/wiki/Version2.0Roadmap

Can begin testing for compatibility and bugs now.

Django 2.0 is not backwards compatible with Django < 1.11, so support was dropped. The backwards compatibility is documented:

https://docs.djangoproject.com/en/dev/internals/release-process/#deprecation-policy

Supports schedules documented:

https://www.djangoproject.com/download/#supported-versions

### CODE REVIEW

**Comment by llazzaro** [comment]
I like this PR. but if I merge it it will break current deploys.
is there any way to support <1.11 also? 2.0 was not yet released.

**Comment by jdufresne** [comment]
> but if I merge it it will break current deploys.

It would eventually be a new release. I envisioned this would only get merged, when you're ready to start supporting Django 2.0. Probably before the release but maybe not right now. If you plan to cut one more release before supporting Django 2.0, I recommend holding off on merging this until that release.

> is there any way to support <1.11 also

It would entail a large number of backward compatibility hacks and workarounds. The Django release process is design with a "loose" semantic versioning system such that 1.11 will be LTS. Django 2.X will be backwards compatible with 1.11 but not < 1.11. For maintainability, I'd prefer to avoid these workarounds. Do you see these workarounds as a hard requirement of merging this?

> 2.0 was not yet released.

Yup. I'm testing and fixing libraries I use so as to have a minimal delay once Django 2.0 is officially released. Please feel free to hold off on merging if you have reasons to delay support.

**Comment by llazzaro** [comment]
@jdufresne I will merge this as soon django 2.0 is released!

**Comment by jdufresne** [comment]
Updated to now test against the release instead of the alpha.

**Comment by llazzaro** [comment]
Thank you! I will try to make some time this night to help on this fork.

**Pull request merged**
