### PR TITLE
Remove example project

### PR DESCRIPTION
**Pull request by westphahl**

### CODE REVIEW

**Comment by llazzaro** [comment]
I agree on this change, actually I did it on the develop branch.
However some people could be using this views, that's why I created this project https://github.com/llazzaro/django-scheduler-views but I didn't finish it yet.
this is to maintain backwards compatibility.

**Comment by llazzaro** [comment]
I will merge after checking old views will work if you install the other project.

**Comment by westphahl** [comment]
The reason why I discarded the pull request is that the tests depend too much on the views/urls. I think it's more work to clean that up.

**Comment by llazzaro** [comment]
ok! don't worry I started doing it on the develop branch, but it will take some time

**Pull request closed without merging**
