### PR TITLE
Factor out tests in separate directory

### PR DESCRIPTION
**Pull request by westphahl**

### CODE REVIEW

**Comment by llazzaro** [comment]
seems that some conflicts need to be solved.
to fix the coverage % add the tests directory to the omit in https://github.com/llazzaro/django-scheduler/blob/master/.coveragerc or I can do it.

thanks :+1:

**Comment by westphahl** [comment]
I added the tests directory but it seems it's still not the same coverage as before. Just not sure if it was correct before.

**Comment by westphahl** [comment]
Think I fixed it :)

**Comment by llazzaro** [comment]
awesome! many thanks! I will try to increase the coverage after merging this pull request!

**Pull request merged**
