### PR TITLE
Added timezone param to api_occurrences().

### PR DESCRIPTION
**Pull request by mikekeda**
PR for issue #325

Added support for timezone param in api_occurrences() function to make possible api calls with timezone param, for example:
```
$('#calendar').fullCalendar({
    events: '/schedule/api/occurrences?calendar_slug=test&timezone=America/Chicago'
});

```
Param timezone is described in https://fullcalendar.io/docs/timezone/timezone/

### CODE REVIEW

**Comment by llazzaro** [comment]
I will review pr soon thanks

**Comment by mikekeda** [comment]
Any updates?

**Comment by llazzaro** [comment]
I will release 0.8.5 today with these changes

**Comment by mikekeda** [comment]
thanks

**Pull request merged**
