### PR TITLE
Fixes never ending occurrences of events

### PR DESCRIPTION
**Pull request by mpaolino**
Related to #283, this PR makes sure that occurrences generation takes into consideration the end_recurring_period.

### CODE REVIEW

**Comment by mpaolino** [comment]
Let's improve coverage.

**Comment by sushovan23** [comment]
@mpaolino : Could you confirm the issue with get_occurrence() in views.py 
It's breaking edit occurrences feature as it is None as occurrence

**Comment by mpaolino** [comment]
I don't think I can increase coverage anymore without adding tests that have nothing to do with this PR. Also I'm not sure why coverails complains about a decreased coverage in scheduletags.py when I didn't change a single line of that file in this PR. Any tips @llazzaro ?

**Comment by llazzaro** [comment]
@mpaolino no idea why the coverage is worst, don't worry about that.

**Pull request merged**
