### PR TITLE
I don't understand this

### PR DESCRIPTION
**Pull request by gabn88**
Could someone please help me understand this line?

### CODE REVIEW

**Comment by llazzaro** [comment]
What you comments is the wrong way of doing it. 
If we need to increment pk, the db should do it....no the python code.

**Comment by gabn88** [comment]
Why is this then in the code?

**Comment by gabn88** [comment]
I really don't understand it, because if occurences get added in between when the calendar is loaded and when you do an edit based on the id, you will edit the newly added occurence instead of the one you selected. I would say better is to not give an id, when the occurence is not persistent?

I feel I want to use only the models from this module and write the rest myself. However, before I use it, I first need to understand it.

I also don't understand this "with_metaclass(ModelBase, *get_model_bases())" instead of models.Model that is called when instantiating the models. Maybe you can help me with that too?

**Comment by llazzaro** [comment]
I will review this soon. probably I will clean up some code that you commented.
thanks for reviewing this.

**Comment by nwaxiomatic** [comment]
Sorry I never saw this issue. The code isn't doing what it "says" its doing, its using a weird algorithm to get an id for the occurrences in fullcalendar (NOT THE SAME AS IN THE DB) which are always unique.

The issue arises because in general you want moving an event to move every unpersisted occurrence of that event (like editing the event), so you need to give all of the unpersisted occurrences the same id so they move together, but those id's can't interfere with the id's of the persisted occurrences, so I give them all the same id = (largest id of any persisted occurrence in the database ) + 1 + event_id, making sure each group is unique, but the same within the group.

**Comment by nwaxiomatic** [comment]
Also if you have any comments about the functionality of the fullcalendar app as it stands, please contribute! I built that aspect without any other input, so I had to make some guesses about how people would "want" it function, so I'd love to update it to be more helpful for users!

**Comment by llazzaro** [comment]
ok. it will be great to have a pr with some comments if you can do it. When I checked the code I though other thing

**Comment by gabn88** [comment]
@nwaxiomatic Thank you for your explanation. I don't use django-scheduler now, because of exactly this line that you explained. 

Let me explain why.
What happens when another users adds some persisted occurrences into the database? The persisted and unpersisted occurrences might overlap, right? In my case this might be a huge issue.

**Comment by nwaxiomatic** [comment]
It won't, actually. These ids are only viewing id's used by fullcalendar, they are unrelated to the id's in the database. If another user adds a persisted occurrence, if you reload the page then it fixes itself with updated fullcalendar id's, and if you were to move occurrences around without reloading, fullcalendar never even sees the new persisted occurrences, so it's no issue. I assure you I have checked all of the cases for this.

**Comment by nwaxiomatic** [comment]
Try to actually break it the way you are describing, and I'm sure it won't actually. The language for the code is just very strange because you have to think about what fullcalendar is expecting and what it sends back to the event changing api's separate from the actual database/django language.

**Comment by gabn88** [comment]
I understand the reloading case.

But without reload you might come into trouble. Even although you might use a different ajax call for unpersisted and persisted event (assumption 1), and the event_id is a large number (assumption 2), eventually enough events might be added so that the generated id also occurs as the id of a persisted occurance. At that point, deviating from you API will cause a leak, because you do not generate the ids on the database level. In my humble opinion the only real way to circumvent this is to generate the ids on the database level, or not to use the ids. Maybe use a string instead.

**Comment by nwaxiomatic** [comment]
If you can actually demonstrate this failing, I'd be interested, but I have already checked the specific case you are talking about and it doesn't fail with the given code.

I think you are missing the fact that there is also a "persisted" boolean value that tells it whether to change the event, using the "event_id" or the occurrence with the specified "id".

**Comment by nwaxiomatic** [comment]
Or could you outline the specific test case you think would fail action by action?

**Comment by gabn88** [comment]
Ah, that's right! Completely missed that bool. That is another way to solve the same issue :+1:  Might be good to mention it in the comments/documentation for folks that want to deviate from the default views/api (like myself).

**Comment by nwaxiomatic** [comment]
Yeah, I'm super bad about commenting any code, I'll try to fix that documentation soon.

**Comment by llazzaro** [comment]
Ok I added docs and unit test here 4059ab3. great to see that the code is working.
First time when I saw it it was ok for me, later review raised some alarms.

**Pull request closed without merging**
