### PR TITLE
Class-based edit/create event views

### PR DESCRIPTION
**Pull request by nwaxiomatic**
added class-based views for editing and creating events

### CODE REVIEW

**Comment by llazzaro** [comment]
don't worry about failed test, I think they need to be updated.

**Comment by nwaxiomatic** [comment]
I made an error with the next url

should it just send you to the event description?

**Comment by nwaxiomatic** [comment]
I need to rewrite the tests to reflect this class change, will look into.

**Comment by nwaxiomatic** [comment]
I just finished up the rewriting of every view as class based, it'd be helpful to have someone else look over this for best practices, but I think it's all good!

**Comment by nwaxiomatic** [comment]
I removed the 'back_url' related things because I couldn't think of good reason to keep them...

**Comment by llazzaro** [comment]
I will merge this pull, please give me some time to do it!

thanks for this improvement

**Comment by nwaxiomatic** [comment]
no worries!

**Comment by rayrrr** [comment]
The failing test assertion is here: https://github.com/llazzaro/django-scheduler/blob/master/tests/test_views.py#L138-L139

**Comment by nwaxiomatic** [comment]
I've never done much with tests... what is that line doing exactly? It could have something to do with args vs kwargs. I'm not sure I spent a ton of time dealing with the args in the views.

**Comment by llazzaro** [comment]
I will check why this is failing, don't worry

**Pull request merged**
